### ISSUE TITLE
Does not work with dbType ISAMTransCompatible

### ISSUE THREAD

**Issue by Spacelord-XaN** [FireflyMigration/enable-transactions-for-old-isam-apps#1]
I am not sure about uploading firefly code to github, so I opened an issue instead of making a pull request. But if it is ok I can provide the changes with a pull request, or here in the comments.

The BtrieveToSQLMigrationManager.InitSQL method uses 'ISAMTransCompatible' as dbType which leads to the use of an IsamTransactionCompatibleEntityDataProvider instead of a NoTransactionEntityDataProvider.

But the changes to make in the IsamTransactionCompatibleEntityDataProvider  are very similar to the changes in the NoTransactionEntityDataProvider.

**Comment by noam-honig** [comment]
@Spacelord-XaN,

I think that all the required changes to the "ISAMTransCompatible" class can be done in the "ConnectionManager.cs" file that is already shared here.

Can you make a pull request that will just affect it? will that be enough?

If so, that could be good.

**Comment by noam-honig** [comment]
Thanks - close the issue if you're ok with it
